#!/bin/bash
#
# Description: CloudStats Monitoring installer script
#
#

# installation folder
install_dir="/home/monitoring_agent"
echo "Monitoring agent will be installed in: " $install_dir

if [ -x "$install_dir/cloudstats.py" ]; then
  echo "Removing the old agent"
  sed -i '/cloudstats/d' /etc/crontab &> /dev/null
  killall -13 -r 'cloudstats' 2>/dev/null
  rm -rf $install_dir
fi

if [ -x "/etc/init.d/cloudstats-agent" ]; then
  echo "Stopping the agent"
  /etc/init.d/cloudstats-agent stop
fi

if [ -x "/etc/init.d/monitoring-agent" ]; then
  echo "Stopping the agent"
  /etc/init.d/monitoring-agent stop
fi

echo "Attempting to install necessary package: tar gzip sysstat iproute2 net-tools"
if [ -e /etc/debian_version ]
then
  apt-get install tar gzip sysstat iproute2 net-tools -y > /dev/null
fi

if [ -e /etc/redhat-release ]
then
  yum install tar gzip sysstat net-tools iproute2 -y > /dev/null
fi


mkdir -p $install_dir
cd $install_dir

# downloading the package based on arch
archs=`uname -m`
echo "Downloading ... "

if [ ${archs} = 'x86_64' ]; then
  curl -L -O --fail 'https://cloudstatsstorage.blob.core.windows.net/agent/monitoring-agent-latest-linux-x86_64.tar.gz'
else
  archs='x86'
  curl -L -O --fail 'https://cloudstatsstorage.blob.core.windows.net/agent/monitoring-agent-latest-linux-x86.tar.gz'
fi

# extracting and placing the files in the right location
echo "Extracting ... "
tar zxvf monitoring-agent-latest-linux-$archs.tar.gz --strip-components 1 >/dev/null
cp init.d/monitoring-agent /etc/init.d/
rm -rf monitoring-agent-latest-linux-$archs.tar.gz

# set permissions and auto start at boot
echo "Installing ... "
chmod 755 /etc/init.d/monitoring-agent
 if [ -e /etc/debian_version ]
  then
    update-rc.d -f monitoring-agent defaults > /dev/null
  fi

  if [ -e /etc/redhat-release ]
  then
    chkconfig monitoring-agent on
  fi

echo "Setting up the account key"
./monitoring-agent --setup "$@"

/etc/init.d/monitoring-agent start

echo "Installation finished."

echo "Running for the first time"
./monitoring-agent --first-time
