FROM centos:latest

RUN curl https://monitoringagent.blob.core.windows.net/agent/monitoring-installer | sh -s cmBS5j5hvkrc-0mv2uLVtol8kdhAzw4uAVSy9QrbSRUBCKtRyK5-jzfisrDUfntmQpgkNupCQPu5GIG23be1FXw

CMD '/home/monitoring_agent/monitoring-agent'
